### ISSUE TITLE
参考xp里aggregation插件的排序

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/intention-tower-knowledge-graph#16]
![图片](https://github.com/tiddly-gittly/intention-tower-knowledge-graph/assets/3746270/d0743d59-29e7-4eb6-87df-3fd196333ea4)

以便在不增加表格列选项内容的情况下排序。目前 dynamic table 要点击标题排序，就得多一列，会很挤。

**Comment by dongrentianyu** [comment]
这个我刚研究了一下，很好实现。安装aggregation插件，然后再导入三个文件。修改原来动态表格里的内容。但有一个问题是，这个插件和itonnote主题有冲突。因为itonnote主题会隐藏不必要的搜索框内容。所以可能就需要考虑换个主题或者修改itonnote主题内容。

另一个问题是，放在侧边栏的话，需要给侧边栏足够的空间，不然还需要手动移动一下。

![image](https://github.com/tiddly-gittly/intention-tower-knowledge-graph/assets/109711900/38bf4cf5-6fc3-44ed-b666-56383428c0cb)

像图片里这样，看着还是挺麻烦的。

[aggregation.zip](https://github.com/tiddly-gittly/intention-tower-knowledge-graph/files/11676010/aggregation.zip)

放进压缩包里，解压出来应该是一个json文件，在安装了aggregation插件后，把这个文件拖进去。

调用代码和原有代码基本一致。

```
<$macrocall $name=aggregation  caption=<<caption>> filter=<<get-all-non-completed-leaf-tasks>>  defaultFields="tbl-expand title tags" class="w-100" />
```

**Comment by dongrentianyu** [comment]
[success.zip](https://github.com/tiddly-gittly/intention-tower-knowledge-graph/files/11676059/success.zip)

这里是一个做好的。可以看看。解压出来是一个html文件。

![image](https://github.com/tiddly-gittly/intention-tower-knowledge-graph/assets/109711900/5209bd6a-3dee-42ec-83cb-c56116fde7ec)

如果不调整样式而修改部局的话，效果也不错。

**Comment by dongrentianyu** [comment]
我看了一下代码，比较复杂。如果要做的话，还是直接引入那三个文件进去好了。或者等xp那边更新。

**Comment by linonetwo** [comment]
直接引入也可以，相当于裁剪功能，反正放到单独文件夹，然后说明这是从哪里复制来的，方便以后更新就行

**Comment by dongrentianyu** [comment]
已经解决了。好像忘了在readme里写说明。回头你看发布新版本时写一下。还是在仓库的readme里写一下。

**Comment by dongrentianyu** [comment]
我好像关不了，那等你来关吧。
