### ISSUE TITLE
选项卡内容可以做成可选的吗？

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/intention-tower-knowledge-graph#17]
![image](https://github.com/tiddly-gittly/intention-tower-knowledge-graph/assets/109711900/8bcabdb1-6a79-427b-b54b-4b4b1b8de334)

比如这部分内容，我可能用不到日历的功能，就会想要去除。但修改插件源码就比较麻烦，虽然也可以做到。我觉得修改成设置里可选的比较好。

另外一个问题是，如果日历功能要作为附带的话，是不是应该像super tag插件一样附带下载呢？

另一个问题是，好像很多插件仓库都没有开discuss版块。这样有时只是想法或者提议也变成issue了。不过好像也没什么。

**Comment by linonetwo** [comment]
觉得有必要改的就放 issue。

日历是 depends 呀，应该 CPL 会自动下载。

这个可选估计得参考官方的设置怎么弄，我也得从头学习参考，你有需要你可以学个试着改看看，反正目前是靠 

https://github.com/tiddly-gittly/intention-tower-knowledge-graph/blob/master/src/ViewTemplate/UnderTask/UnderTask.tid

这里的筛选器来获取有哪些tab的

**Comment by linonetwo** [comment]
发布了个新版的

**Comment by dongrentianyu** [comment]
这么快就发布吗？本来我还想着要不要再改一些其他的内容。但xp的那个确实不好放进去。

**Comment by dongrentianyu** [comment]
主要是这个任务管理插件已经附带了很多其他插件了。我感觉基本上都需要重新开一个wiki来放了。要是能减少插件依赖就好了。

**Comment by linonetwo** [comment]
其实这样才轻量，说明大多数东西都是复用别的功能，这个插件自身功能不多。主要是那些插件大都是我本来就装了的，相当于是在自己wiki里改出来的功能，只不过抽出来变成插件了而已

**Comment by dongrentianyu** [comment]
对插件来说是轻量了，对wiki来说是增加了。

**Comment by dongrentianyu** [comment]
想了想。xp那个还是先不加进去了，感觉可能其他人并没有这样的需要。我试着改一些文档内容吧，改了再提交一下pr，然后就可以删除fork仓库了。

**Comment by linonetwo** [comment]
xp 那个主要是为了修复目前表格无法排序的问题吧，应该还是需要的

**Comment by dongrentianyu** [comment]
那后面更新了文档，我看看怎么加进去。另外有一个问题是`intention-tower-knowledge-graph`插件名会不会太长了，感觉直接缩写成`ITKG`，更方便，也更有利于传播吧。只是我不知道怎么改，我怕一改其他的都要改。

**Comment by dongrentianyu** [comment]
![image](https://github.com/tiddly-gittly/intention-tower-knowledge-graph/assets/109711900/703f1cf2-b2df-4930-96cd-698ec5b4c19a)

用xp的话，就是会占用比较大的空间。因为上面还有一个搜索，甚至可筛选的内容。

图谱那个不改吗？我觉得现在的图谱还是有些复杂了。我分多次pr来实现吧。这样你看什么改得可以就合并，改得不好就不合并。
