### ISSUE TITLE
是不是应该给特定标签加上前缀来区分其他标签？

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/intention-tower-knowledge-graph#19]
比如添加意义条目，会自动附带上意义标签。当然这是为了后面超级标签使用。不过我在想，如果一个人之前就已经有意义条目了，而且意义条目背后可能不是这类似的，会不会造成困扰呢？实际上我自己就有遇到过。

我觉得加上把`意义`标签改成`ITKG-意义`比较好。也就是加上`ITKG`作为前缀。一般来说不会特意用这个词语。其他项目或者任务也是同理。

**Comment by linonetwo** [comment]
设置里可以改

**Comment by dongrentianyu** [comment]
了解了
