### ISSUE TITLE
是否应该把已完成的项目列出来

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/intention-tower-knowledge-graph#26]
我发现项目列表里只会列出正在进行的，或者新任务，不会列出完成了的任务列表。

![image](https://github.com/tiddly-gittly/intention-tower-knowledge-graph/assets/109711900/3ba40f6d-5405-42b5-9ed6-4642d1982b55)

因为有时我会记不起某个任务是不是已经完成了，还是因为没记下来。就得手动搜索一下了，感觉可以把已经完成的任务列表也在旁边列出来。

**Comment by linonetwo** [comment]
你看网站上的项目，其实我早就想到过了。还是看网站上的todo吧，这个仓库的issue尽量都搬到网站上，试用这个产品

**Comment by dongrentianyu** [comment]
原来网站上的内容既作为示例，也作为待办啊。那也行，不过现在有了aggregation插件，应该可以很方便调用。等会我提个pr吧，趁现在还没有改版本号。
