### ISSUE TITLE
递归安装依赖插件问题没有得到解决

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/intention-tower-knowledge-graph#32]
也就是日历插件并没有安装。即使我把依赖的两个插件也同样写在依赖字段里了。我猜想这应该是太微的一个保护机制或者是无法进行依赖解析。

但在Version v0.8.0.版本里没有出现报错。可能是修复了。

等过段时间再看看能不能解决吧。这个确实还挺麻烦的。官方那边还没有太多的回复。

**Comment by linonetwo** [comment]
最新版 CPL 搞定了，关了

**Comment by linonetwo** [comment]
不过说实话我还没试过

**Comment by dongrentianyu** [comment]
搞个测试插件，试一下就好了。回头我试着搞一下。
